import assets from "../assets/assets";

const data = {
    pools: [
        {
            'name': 'Redondeta',
            'desc_corta':'Proyecto realizado con venecitas biseladas y un borde atermico de 12x4".',
            'color':'white',
            'desc_larga': '_Caracteristicas:_\nPiscina *sin* secciones *rectas*,revestida con *venecitas biseladas* con una superficie de *680* pies cuadrados.\nEl *borde atérmico* de esta obra de arte de *12x4* pulgadas, tan *funcional* como *estético*.\nEn tan solo *6 días* hemos completado el gran desafío que presenta una piscina de estas características consiguiendo un *acabado único*.\n _Materiales de adherencia:_\n Contamos con la *experiencia* para trabajar con pegamento poxilina, grau epoxi o klaukol para venecitas. El puente de adherencia también puede ser klaukol, como cal y cemento. Para el borde atermico contamos con cal o agua y cemento, utilizando como puente de adherencia entre éstos y el borde klaukol o taculu respectivamente. *Cualquier opción* junto a nosotros aseguran una conexión *sólida* y *duradera* en el tiempo.\n*No dude* en *consultarnos* por el material de su preferencia.',
            'portada': "/images/Redondeta/pileta 6.jpeg",
            'tiempo':'6 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Sin secciones rectas',
            'demas_fotos':["/images/Redondeta/pileta 6.jpeg", "/images/Redondeta/union 2.jpeg", "/images/Redondeta/constr.jpeg",
             "/images/Redondeta/constr 2.jpg", "/images/Redondeta/constr 3.jpg","/images/Redondeta/antes.jpg"],
             "imgdesc1":'/images/Redondeta/union 2.jpeg',
             "imgdesc2":'/images/Redondeta/constr 2.jpg',
             "imgdesc3":'/images/Redondeta/antes.jpg',
             "desc1":'En esta sección de del revestimiento tenemos una concavidad tanto en la pared como en el faldón, cortamos con discos diamantes de 4” las venecitas logrando cortas precisos y suaves el tacto. Además cuidamos la integridad del material trabajando sobre las condiciones climáticas adecuadas.',
             "desc2":'El proceso de construcción comienza en la zona superior de la piscina, se colocan las planchas cortadas de venecitas bajando por las paredes, luego colocamos el suelo y dejamos las uniones para el final. Tanto las venecitas como el borde se adhieren utilizando una primera capa de pegamento, y luego un puente de adherencia entre ésta y el material, logrando una conexión sólida y duradera en el tiempo.',
             "desc3":'Podemos observar la notoria diferencia estética entre una piscina con y sin revestimientos. Además las venecitas agregan una textura y suavidad, lograda al cuidar cada unión entre las piezas colocadas, realmente únicas. '
        },
        {
            'name': 'Finlandesa',
            'desc_corta':'Finura trabajada con venecitas biseladas, en piscina y jacuzzi.',
            'color':'white',
            'desc_larga': `_ Características:_\nPiscina *majestuosa* con una superficie de *1100* pies cuadrados, revestida con *venecitas biseladas*.El *borde atérmico* de esta obra de arte de *12x4* pulgadas, concluye la *elegancia* de esta piscina.Con *8 días* hemos completado esta inmensa piscina, con un jacuzzi a la altura, donde resaltamos en cada unión y sección, por la prolijidad de las intersecciones y de la *nivelación*. \n\n _Materiales de adherencia:_\n Contamos con la experiencia para trabajar con pegamento poxilina, grau epoxi o klaukol para venecitas. El puente de adherencia también puede ser tanto klaukol, como cal y cemento. Para el borde atermico contamos con algunas opciones podrían ser utilizando cal y como puente de adherencia klaukol, o por otro lado agua y cemento, con el puente de adherencia taculu. *Cualquier opción* junto a *nosotros* aseguran una conexión *sólida* y *duradera* en el tiempo.\n*No dude en consultarnos por el material de su preferencia.*`,
            'portada': "/images/Finlandesa/adentro.jpeg",
            'tiempo':'8 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Reduadrada y Nivelada',
            'demas_fotos':["/images/Finlandesa/Pileta 3.jpeg","/images/Finlandesa/jacuzzi.jpeg","/images/Finlandesa/Detalle 1.jpeg",
            "/images/Finlandesa/adentro.jpeg","/images/Finlandesa/Detalle 2.jpeg","/images/Finlandesa/detalle 3.jpeg",
            "/images/Finlandesa/escalera 1.jpeg","/images/Finlandesa/escalera 2.jpeg","/images/Finlandesa/escalera 3.jpeg"],
            "desc1":'Esta majestuosa e inmensa piscina, se encuentra perfectamente nivelada desde la piscina hasta el jacuzzi en cada cm2, aunque el proceso de nivelación y recuadre puedan agregar días de trabajo, nos permiten llevar al límite nuestras habilidades  ofreciendo un acabado impresionante en cada sección. ',
            "desc2":' Nuestra precisión no solo se muestra en nuestra habilidad para nivelar, si no también en el uso de herramientas de corte, en este caso utilizando discos diamantados de 4”, logrando por ejemplo esta unión donde la venecita comienza en 2 cm y termina en un alto de tan solo 0,2 cm, con esto logramos uniones más suaves a la vista, pero por sobretodo al tacto.  ',
            "desc3":' Esta sección en la escalera es el reflejo de nuestra habilidad para la nivelación, tan solo con observar la rectitud en cada venecita, no hace falta agregar palabras.aprovechamos a contar que tanto para la colocación de las venecitas como de los bordes, utilizamos una primera capa de pegamento y luego el puente de adherencia, esta forma de colocacion asegura la maxima solidez y duración en el tiempo. ',
            "imgdesc1":'/images/Finlandesa/Pileta 3.jpeg',
            "imgdesc2":'/images/Finlandesa/detalle 3.jpeg',
            "imgdesc3":'/images/Finlandesa/Detalle 2.jpeg'
        },
        {
            'name': 'Argentineta',
            'desc_corta':'La inmensidad recubierta en venecitas biseladas y travertina utilizada en todo el piso aledaño.',        
            'color':'white',    
            'desc_larga': '_ Características:_\nEsta inmensa piscina cuenta con una superficie de *1500* pies cuadrados, revestida con *venecitas biseladas*. El borde atermico de 12x12 pulgadas en toda la zona, agrega seguridad y comodidad como ninguna otra. A pesar del tamaño, sumado al jacuzzi en el cual *cuidamos el detalle* de cada unión, tan solo tardamos *7 días*. \n\n _Materiales de adherencia:_\n *Ofrecemos* siempre la posibilidad a nuestros clientes de elegir los materiales de *su preferencia.*\n Algunas opciones para las venecitas pueden ser grau epoxi o klaukol para venecitas y como puente de adherencia puede ser tanto klaukol, como cal y cemento. Para el borde atermico podrían ser utilizando cal y como puente de adherencia klaukol, o por otro lado agua y cemento, con el puente de adherencia taculu.\n *Insistimos en que no dude en consultarnos por otros materiales, junto a OCC tendrá asegurada la mayor solidez y duración*',
            'portada': "/images/Argentineta/portada.jpeg",
            'tiempo':'6 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Reduadrada y Nivelada',
            'demas_fotos':["/images/Argentineta/portada.jpeg", "/images/Argentineta/decote.jpg", "/images/Argentineta/jaquzzi.jpeg"],
             "desc1":'La mejor forma de mostrar nuestra atención al detalle es mostrando esta imagen, donde se puede apreciar la perfecta nivelación de las venecitas, la suavidad del empalme entre la pared y el descanso o apreciar la perfecta curva que hacen sobre el banco. Todo esto logrado utilizando un disco diamantado de 4” para cada corte. ',
             "desc2":'Este nivel de precisión lo mantenemos a lo largo y ancho de toda la piscina, incluso en inmensidades como esta. logrando así transiciones limpias y suaves, que agradecerá cada vez que camine en el fondo de su piscina.',
             "desc3":'El borde atermico proporciona no solo elegancia, si no que otorga comodidad al tener una sección que nunca se encuentra caliente. Es por esto que cuidamos la colocación utilizando métodos de adherencia de primera calidad para asegurar una duración prolongada en el tiempo.',
             "imgdesc1":'/images/Argentineta/jaquzzi.jpeg',
             "imgdesc2":'/images/Argentineta/portada.jpeg',
             "imgdesc3":'/images/Argentineta/Borde.jpeg'
        },
        {
            'name': 'Fuente',
            'desc_corta':'Esta majestuosa fuente utiliza porcelanato, marmol, simil madera y el borde atermico.',
            'color':'black',
            'desc_larga': `_ Características:_\nEste es nuestro trabajo más grande si de superficies hablamos, una fuente de *4000* pies cuadrados, revestida con *venecitas biseladas*, un borde atermico que rodea la zona y secciones internas calefaccionadas, trabajadas en mármol y porcelanato(simil madera) \n\n _Materiales de adherencia:_\n  En este trabajo tenemos 4 materiales distintos a colocar, asi que por un lado en las venecitas utilizamos pegamento poxilina, grau epoxi o klaukol para venecitas, las secciones de porcelanato y marmol están selladas con mastic para mármol, por último para el borde atermico también ofrecemos diversas opciones en su instalación, como puede ser la cal o agua y cemento; utilizando como puente de adherencia entre éstos y el borde klaukol o taculu respectivamente.\nEn caso de no ver el material de *su preferencia* no dude en *escribirnos*, siempre ofrecemos una conexión *duradera y sólida* con los medios que usted elija.  `,
            'portada': "/images/Fuente/fuente.jpeg",
            'tiempo':'1 mes',
            'ubicacion':'Miami-USA',
            'recuadre':'Sin nivelar',
            'demas_fotos':["/images/Fuente/fuente.jpeg","/images/Fuente/puente.png",'/images/Fuente/centro 2.png'],
             "desc1":' Para proteger la integridad de los materiales, cuidando la fragilidad del mármol, las uniones entre el mármol y porcelanato de cada sección central, son cortadas a 45° (proceso de ingletado) asegurando una unión sólida entre ambas superficies, asegurando resistencia y durabilidad.',
             "desc2":' En esta imagen podemos ver la amplia variedad de materiales que son, la venecita, el mármol y el porcelanato. Todos son instalados por nosotros con el mismo cuidado y prolijidad, ya que contamos con la experiencia para manejar cualquier material a colocar con cualquier material de adherencia.',
             "desc3":'Esta fuente inmensa ha sido una experiencia inolvidable, ya que es nuestro proyecto más grande y con mayor variedad de materiales.',
             "imgdesc1":'/images/Fuente/detalle.jpeg',
             "imgdesc2":'/images/Fuente/centro 2.png',
             "imgdesc3":'/images/Fuente/fuente 2.jpeg'
        },
        {
            'name': 'Piscina',
            'desc_corta':'Trabajo realizado con venecitas biseladas y un borde atermico de 12x4".',
            'color':'white',
            'desc_larga': `Explora la comodidad y el diseño con nuestra piscina de *900 pies cuadrados*, revestida con venecitas biseladas. El borde atermico de 4x12 pulgadas destaca por su *estilo moderno* y funcionalidad cuando no estás sumergido. El proceso de instalación, hábilmente realizado en *5 días*, garantiza un equilibrio perfecto entre *eficiencia* y *calidad*. \n\n_Procedimiento:_ \nLas venecitas se cortan utilizando discos diamantados de 4”, utilizando esto y nuestra mano de obra especializada, aseguramos cortes *limpios*, *prolijos* y nunca una ruptura innecesaria. Luego se colocan utilizando klaukol para venecitas, pegamento poxilina o grau epoxi a *su preferencia* o *disponibilidad*, contamos con la *experiencia* para garantizar la *resistencia* y *durabilidad* necesarios para afrontar los rigores del tiempo y uso diario con el material de su preferencia.\nAsí mismo el borde atermico se instala utilizando cal y como puente de adherencia klaukol, también puede reemplazarse por agua y cemento con puente de adherencia taculu. Donde ambas opciones aseguran una conexión *sólida* y *duradera* en el tiempo entre el borde y la superficie de colocación.`,
            'portada': "/images/Clasica/detalle.jpeg",
            'tiempo':'5 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Sin recuadrar',
            'demas_fotos':["/images/Clasica/detalle.jpeg","/images/Clasica/escalera.jpeg","/images/Clasica/proceso.jpeg",
            "/images/Clasica/transicion.jpeg","/images/Clasica/Portada.jpeg","/images/Clasica/WhatsApp Image 2023-10-30 at 11.43.14 (1).jpeg"],
             "desc1":' El proceso de instalación se realiza comenzando por las paredes y el suelo, dejando para el final el empalme entre estos, logrando así una unión prolija, esto es muy importante en piscinas de faldón curvo.',
             "desc2":'Esto puede apreciarse en la suavidad del acabado de esta unión, que además no presenta ningún relieve que puedas sentir más que los bordes suaves de la propia venecita.',
             "desc3":'Puede apreciarse la inmensidad de esta piscina de casi 1000 pies cuadrados, es por eso que nos orgullecemos de resaltar la rapidez en la realización de la obra, siendo de tan solo 5 días.',
             "imgdesc1":'/images/Clasica/proceso 2.png',
             "imgdesc2":'/images/Clasica/detalle 2.png',
             "imgdesc3":'/images/Clasica/detalle.jpeg'
        },
        {
            'name': 'Multicolor',
            'desc_corta':'Arcoiris realizado con venecitas biseladas multicolor y borde atermico de 12x4".',
            'color':'white',
            'desc_larga': `_ Características:_\nEsta piscina se encuentra sobre el agua del lago aledaña, cuenta con una superficie de *840* pies cuadrados, revestida con *venecitas biseladas* (el borde atérmico no es colocado por OCC). Este trabajo fue un gran desafío, por los riesgos de levantamiento, así todo los acabados son prolijos y perfectamente nivelados, tardando tan solo 6 días en finalizar. 
            \n\n _Materiales de adherencia:_\n *Ofrecemos* siempre la posibilidad a nuestros clientes de elegir los materiales de *su preferencia.*\n Algunas opciones para las venecitas pueden ser grau epoxi o klaukol para venecitas y como puente de adherencia puede ser tanto klaukol, como cal y cemento. Para el borde atermico podrían ser utilizando cal y como puente de adherencia klaukol, o por otro lado agua y cemento, con el puente de adherencia taculu.\n *Insistimos en que no dude en consultarnos por otros materiales, junto a OCC tendrá asegurada la mayor solidez y duración*`,
            'portada': "/images/LGBT/Portada.jpeg",
            'tiempo':'6 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Reduadrada y Nivelada',
            'demas_fotos':["/images/LGBT/Portada.jpeg","/images/LGBT/portada 2.jpeg","/images/LGBT/Porceso.jpg",
            "/images/LGBT/proceso 2.jpeg", "/images/LGBT/detalle 4.jpeg", "/images/LGBT/Detalle.jpeg"],
             "desc1":' Durante este trabajo, como puede verse teníamos un orificio del cual brotaba el agua constantemente, por la presión ejercida del agua circundante que se encuentra a mayor altura. El procedimiento fue colocar el revestimiento de paredes y pisos con el paso a paso normal, dejando para el final el orificio central.',
             "desc2":'Como se observa, a pesar de la complejidad las terminaciones son impecables, suaves y perfectamente rectas y paralelas. Las venecitas son cortadas con discos diamantados de 4” y colocadas con una primera capa de pegamento y luego el puente de adherencia entre éste y las venecitas. Con esto aseguramos la mayor solidez y duración gracias al correcto tratamiento de la superficie a colocar. ',
             "desc3":'Luego de 5 días de trabajo con un bomba constantemente encendida, llegamos al momento de sellar el orificio, para eso colocamos dentro de el cemento fulminante y poliuretano, previamente cortamos una plancha de venecitas con el tamaño y forma exactas, tal como la pieza final de un rompecabezas, y se colocó terminando el sellado del orificio. Luego se comenzó el llenado de la piscina asegurando que la presión del agua se equipare con la del lago, evitando así para siempre el riesgo de levantamiento o fisuras en paredes y suelo.',
             "imgdesc1":'/images/LGBT/Porceso.jpg',
             "imgdesc2":'/images/LGBT/detalle 4.jpeg',
             "imgdesc3":'/images/LGBT/proceso 2.jpeg'
        },
        {
            'name': 'Clasica',
            'desc_corta':'Trabajo realizado con venecitas biseladas y un borde atermico de 2x1 pie.',
            'color':'white',
            'desc_larga': `Sumérgete en esta piscina de *650 pies2*, revestida con venecitas biseladas. Su borde atermico de 2x1pie proporciona *elegancia* y también mejora la *seguridad* y *comodidad* de tu experiencia. Nuestros *años* de *experiencia* perfeccionando el *arte* de la instalación nos han llevado a realizar este proceso en tan solo *2 días*. \n\n_Procedimiento:_\nLas venecitas se cortan utilizando discos diamantados de 4”, utilizando esto y nuestra *mano* de obra *especializada*, aseguramos cortes limpios, prolijos y nunca una ruptura innecesaria. Luego se colocan utilizando pegamento poxilina o grau epoxi, el *material* de *adherencia* es a *decisión del cliente*, contamos con la *capacitación* para *trabajar* con lo que se desee. Ambos garantizan la *resistencia* y *durabilidad* necesarios para afrontar los rigores del tiempo y uso diario. \nEl borde atermico se instala utilizando cal y como puente de adherencia klaukol, también puede reemplazarse por agua y cemento y el puente de adherencia taculu. Ambas opciones aseguran una conexión sólida y duradera en el tiempo entre el borde y la superficie de colocación. Al igual que con la adherencia de las venecitas, esto es *su* completa *decisión*.`,
            'portada': "/images/Adefinir/Portada.jpeg",
            'tiempo':'2 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Sin nivelar',
            'demas_fotos':["/images/Adefinir/Panora.jpeg","/images/Adefinir/Detalle.jpeg","/images/Adefinir/Detalle 2.jpeg"],
             "desc1":'A pesar de que en este trabajo la nivelación no fue realizada (a decisión del cliente), los acabados en la pisada de la escalera mantienen siempre finura y suavidad para su comodidad.',
             "desc2":'Esto mismo se ve retratado en el faldón, donde cortando con máxima precisión logramos estas esquinas con una transición suave entre el suelo y la pared, las secciones realizadas en el corte de la plancha de venecitas puede alcanzar hasta los 2 mm.',
             "desc3":'Estos bordes atérmicos son colocados no solo para que duren y afronten el rigor del tiempo y el clima, si no para la estética de la piscina, dando abrocha la elegancia siguiente la forma de este, que hábilmente logramos en la colocación.',
             "imgdesc1":'/images/Adefinir/escalera.png',
             "imgdesc2":'/images/Adefinir/union.png',
             "imgdesc3":'/images/Adefinir/borde.png'
        },
        {
            'name': 'Escaloneta',
            'desc_corta':'Obra realizada con venecitas biseladas y un borde atermico de 12x4".',
            'color':'white',
            'desc_larga': `_ Características:_\nSuperficie de *800* pies cuadrados, revestida con *venecitas biseladas*, cuenta con un borde atermico de 12x4 pulgadas tan estético como funcional. La atención al detalle y eficiencia se reflejan en los tan solo *5 días* de trabajo. \n\n _Materiales de adherencia:_\n *Ofrecemos* siempre la posibilidad a nuestros clientes de elegir los materiales de *su preferencia.*\n Algunas opciones para las venecitas pueden ser grau epoxi o klaukol para venecitas y como puente de adherencia puede ser tanto klaukol, como cal y cemento. Para el borde atermico podrían ser utilizando cal y como puente de adherencia klaukol, o por otro lado agua y cemento, con el puente de adherencia taculu.\n *Insistimos en que no dude en consultarnos por otros materiales, junto a OCC tendrá asegurada la mayor solidez y duración*`,
            'portada': "/images/Escaloneta/detalle.jpeg",
            'tiempo':'5 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Reduadrada y Nivelada',
            'demas_fotos':["/images/Escaloneta/comparativa 1.jpg", "/images/Escaloneta/proceso 1.jpg",
            "/images/Escaloneta/proceso 3.jpg","/images/Escaloneta/detalle.jpeg","/images/Escaloneta/detalle 2.jpeg",
            "/images/Escaloneta/detalle 3.jpeg"],
             "desc1":'Cuando se trata de piscinas de faldón curvo, es importante dejar la unión entre el piso y las paredes para el final, de esta manera aseguramos una transición suave y prolija, esto se logra no solo con el orden de colocación del revestimiento sino también con la delicadeza en los cortes logrados utilizando discos diamantados de 4 pulgadas, y trabajando sobre las condiciones climáticas adecuadas para proteger la integridad del material.',
             "desc2":' Incluso en zonas donde las paredes y la unión con el piso son completamente curvas, logramos un detalle alucinante, consiguiendo suavidad en cada curva y transición. ',
             "desc3":'Cuando nuestra atención al detalle, con nuestra experiencia se suman al pedido del cliente de nivelar logramos un acabado perfecto, y tan duradero como sólido. ',
             "imgdesc1":'/images/Escaloneta/faldon.png',
             "imgdesc2":'/images/Escaloneta/transicion 2.png',
             "imgdesc3":'/images/Escaloneta/detalle 2.jpeg'
        },
        {
            'name': 'Celeste',
            'desc_corta':'Trabajo realizado con cerecita y marmol',
            'color':'white',
            'desc_larga': 'Sumérgete en esta piscina de *720 pies2*, revestida con venecitas biseladas. Su borde atermico de 1 metro cuadrado proporciona *elegancia* y también mejora la seguridad y *comodidad* de tu experiencia. Nuestros *años* de *experiencia* perfeccionando el *arte* de la instalación nos han llevado a realizar este proceso en tan solo *5 días*. \n\n _Procedimiento:_\n Las venecitas se cortan utilizando discos diamantados de 4”, utilizando esto y nuestra *mano* de obra *especializada*, aseguramos cortes *limpios*, *prolijos* y *nunca* una ruptura innecesaria. Luego se colocan utilizando pegamento poxilina o grau epoxi, el material de adherencia es a *decisión* del *cliente*, contamos con la *capacitación* para trabajar con el material de *su* preferencia. \n El borde atermico se instala utilizando cal y como puente de adherencia klaukol, también puede reemplazarse por agua y cemento y el puente de adherencia taculu. Ambas opciones aseguran una conexión *sólida* y *duradera* en el tiempo entre el borde y la superficie de colocación. Al igual que con la adherencia de las venecitas, esto es a *su* completa decisión. En la instalación de venecitas puede utilizarse tambien klaukol para venecitas, estas son algunas de las opciones, pero siempre estamos *disponibles* y listos para *adaptarnos* a *sus* preferencias.',
            'portada': "/images/celeste/frente.jpg",
            'tiempo':'5 Días',
            'ubicacion':'Miami-USA',
            'recuadre':'Reduadrada y Nivelada',
            'demas_fotos':["/images/celeste/frente.jpg", "/images/celeste/escalera.jpeg", "/images/celeste/proceso.jpeg"],
             "desc1":'Como puede observarse a diferencia de las piscinas de faldon curvo, en esta realizamos primero el revestimiento de las 4 paredes hasta llegar al suector del piso mas alto. Luego continuamos con el suelo, y por ultimo la union faltante del piso con las paredes en la parte profunda de la piscina.',
             "desc2":'El proceso de construcción en la escalera consta por las características de este, en recubrirla con el mismo material del borde atérmico, logrando así un contraste armónico entre el interior y exterior de la piscina. En esta sección hay que trabajar cuidadosa y meticulosamente ya que las venecitas están colocadas y podrían romperse fácilmente frente a un descuido en la manipulación de las baldosas.',
             "desc3":'',
             "imgdesc1":'/images/celeste/proceso.jpeg',
             "imgdesc2":'/images/celeste/escalera.jpeg',
             "imgdesc3":''
        },
        
    ]
};

export default data;